name: Yousef Ayman Abdelaziz Shehab 

on:

  push:

    branches:

      - master  
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Before"
        run: ls
      - uses : actions/checkout@v3

      - name: "Afterr"
        run: ls  
      
      - name: "login to dockerhub"
        run: docker login --username ${{ secrets.DOCKERUSR }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: "Docker Build"
        run: docker build -t ${{ secrets.DOCKERUSR }}/yousefaymanshehab .
      
      - name: "Docker Push"
        run: docker push ${{ secrets.DOCKERUSR }}/yousefaymanshehab
